version: '3.8'

services:
  db:
    container_name: pg-container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

  app:
    container_name: app-container
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=test_db
      - JWT_SECRET=utku123
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./.env:/app/.env
      - ./config/config.json:/app/config/config.json 

  etcd1:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: etcd1
    environment:
      - ETCD_NAME=node1
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd1:2380
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2380
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd1:2379
      - ETCD_INITIAL_CLUSTER=node1=http://etcd1:2380,node2=http://etcd2:2381,node3=http://etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2379:2379
      - 2380:2380
    networks:
      - etcd-net

  etcd2:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: etcd2
    environment:
      - ETCD_NAME=node2
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd2:2381
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2381
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2378
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd2:2378
      - ETCD_INITIAL_CLUSTER=node1=http://etcd1:2380,node2=http://etcd2:2381,node3=http://etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2378:2378
      - 2381:2381
    networks:
      - etcd-net

  etcd3:
    image: quay.io/coreos/etcd:v3.5.14
    container_name: etcd3
    environment:
      - ETCD_NAME=node3
      - ETCD_INITIAL_ADVERTISE_PEER_URLS=http://etcd3:2382
      - ETCD_LISTEN_PEER_URLS=http://0.0.0.0:2382
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2377
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd3:2377
      - ETCD_INITIAL_CLUSTER=node1=http://etcd1:2380,node2=http://etcd2:2381,node3=http://etcd3:2382
      - ETCD_INITIAL_CLUSTER_STATE=new
    ports:
      - 2377:2377
      - 2382:2382
    networks:
      - etcd-net


volumes:
  pg-data:

networks:
  etcd-net:
    driver: bridge
